import { Injectable, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class AuthService {
  private supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  private supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  constructor(private prisma: PrismaService) {}

  async signUp(body: any) {
    const { email, password, name, phone } = body;

    // 1. Register the user inside Supabase Auth GoTrue instance
    const response = await fetch(`${this.supabaseUrl}/auth/v1/signup`, {
      method: 'POST',
      headers: {
        'apikey': this.supabaseAnonKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ email, password }),
    });

    const data = await response.json();

 if (!response.ok) {
  // Log this so you can see it in your Nest terminal!
  console.error('Supabase raw error data:', data); 
  
  throw new BadRequestException(
    data.error_description || data.message || 'Invalid email or password'
  );
}

    // 2. Mirror the record inside your Supabase PostgreSQL database via Prisma
    const newUser = await this.prisma.user.create({
      data: {
        id: data.id || data.user?.id, // Use the exact identity ID generated by Supabase
        email,
        name,
        phone,
        role: 'customer',
      },
    });

    return { success: true, user: newUser };
  }

  async login(body: any) {
    const { email, password } = body;

    // Authenticate credentials directly against Supabase API
    const response = await fetch(`${this.supabaseUrl}/auth/v1/token?grant_type=password`, {
      method: 'POST',
      headers: {
        'apikey': this.supabaseAnonKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ email, password }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new BadRequestException(data.error_description || 'Invalid email or password');
    }

    // Returns access_token, refresh_token, and user profile metadata back to Next.js
    return {
      success: true,
      token: data.access_token,
      user: data.user,
    };
  }
}